import React, { Component } from 'react'
import { OctocatArticle } from './components/OctocatArticle'
import { Footer } from './components/Footer'
import { Header } from './components/Header'

export class App extends Component {
  render() {
    return (
      <div>
        <Header />

        <OctocatArticle
          imgLink="https://octodex.github.com//spectrocat/"
          catImg="https://octodex.github.com//images/spectrocat.png"
          catName="Spectrocat"
          Id="44"
          artistLink="https://github.com/cameronmcefee"
          artistImg="https://github.com/cameronmcefee.png"
          artistName="cameronmcefee"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//octocat-de-los-muertos/"
          catImg="https://octodex.github.com//images/octocat-de-los-muertos.jpg"
          catName="OctocatDeLosMuertos"
          Id="55"
          artistLink="https://github.com/cameronmcefee"
          artistImg="https://github.com/cameronmcefee.png"
          artistName="cameronmcefee"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//octobiwan/"
          catImg="https://octodex.github.com//images/octobiwan.jpg"
          catName="OctobiWanCatnobi"
          Id="3"
          artistLink="https://github.com/cameronmcefee"
          artistImg="https://github.com/cameronmcefee.png"
          artistName="cameronmcefee"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//nyantocat/"
          catImg="https://octodex.github.com//images/nyantocat.gif"
          catName="Nyantocat"
          Id="84"
          artistLink="https://github.com/cameronmcefee"
          artistImg="https://github.com/cameronmcefee.png"
          artistName="cameronmcefee"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//stormtroopocat/"
          catImg="https://octodex.github.com//images/stormtroopocat.png"
          catName="Stormtroopocat"
          Id="84"
          artistLink="https://github.com/jeejkang"
          artistImg="https://github.com/jeejkang.png"
          artistName="jeejkang"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//daftpunktocat-guy/"
          catImg="https://octodex.github.com//images/daftpunktocat-guy.gif"
          catName="Daftpunktocat-Guy"
          Id="100"
          artistLink="https://github.com/jeejkang"
          artistImg="https://github.com/jeejkang.png"
          artistName="jeejkang"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//daftpunktocat-thomas/"
          catImg="https://octodex.github.com//images/daftpunktocat-thomas.gif"
          catName="Daftpunktocat-Thomas"
          Id="100"
          artistLink="https://github.com/jeejkang"
          artistImg="https://github.com/jeejkang.png"
          artistName="jeejkang"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//mummytocat/"
          catImg="https://octodex.github.com//images/mummytocat.gif"
          catName="Mummytocat"
          Id="105"
          artistLink="https://github.com/tonyjaramillo"
          artistImg="https://github.com/tonyjaramillo.png"
          artistName="tonyjaramillo"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//linktocat/"
          catImg="https://octodex.github.com//images/linktocat.jpg"
          catName="Linktocat"
          Id="108"
          artistLink="https://github.com/cameronmcefee"
          artistImg="https://github.com/cameronmcefee.png"
          artistName="cameronmcefee"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//terracottocat/"
          catImg="https://octodex.github.com//images/Terracottocat_Single.png"
          catName="Terracottocat"
          Id="149"
          artistLink="https://github.com/chubbmo"
          artistImg="https://github.com/chubbmo.png"
          artistName="chubbmo"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//octogatos/"
          catImg="https://octodex.github.com//images/Octogatos.png"
          catName="Octogatos"
          Id="148"
          artistLink="https://github.com/cameronfoxly"
          artistImg="https://github.com/cameronfoxly.png"
          artistName="cameronfoxly"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//dinotocat/"
          catImg="https://octodex.github.com//images/dinotocat.png"
          catName="Dinotocat"
          Id="130"
          artistLink="https://github.com/kimestoesta"
          artistImg="https://github.com/kimestoesta.png"
          artistName="kimestoesta"
        />
        <OctocatArticle
          imgLink="https://octodex.github.com//spidertocat/"
          catImg="https://octodex.github.com//images/spidertocat.png"
          catName="Spidertocat"
          Id="88"
          artistLink="https://github.com/jeejkang"
          artistImg="https://github.com/jeejkang.png"
          artistName="jeejkang"
        />

        <Footer />
      </div>
    )
  }
}
